[package]
name = "minivec"
version = "0.1.1"
authors = ["LeonineKing1199 <christian.mazakas@gmail.com>"]
edition = "2018"
license = "BSL-1.0"
description = "A version of Vec that's only the size of a single pointer"
repository = "https://github.com/LeonineKing1199/minivec"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
